[package]
name = "kanji-practice"
version = "0.1.0"
description = "Create charts with selected kanji for practicing"
repository = "https://github.com/istudyatuni/kanji-practice"
authors = ["Ilia <@istudyatuni>"]
license = "MIT"
keywords = ["kanji"]
disciplines = ["education"]

entrypoint = "lib.typ"
compiler = "0.12.0"
exclude = ["docs/*"]
