[package]
name = "kanji-practice"
version = "0.1.0"
entrypoint = "lib.typ"
compiler = "0.12"

repository = "https://github.com/istudyatuni/kanji-practice"
keywords = ["kanji"]
disciplines = ["education"]
exclude = ["docs/*"]
